### ISSUE TITLE
checkout_externals cannot get ufs-weather-model

### ISSUE THREAD

**Issue by AnnaSmoot-NOAA** [NOAA-EMC/AQM-Workflow#2]
**Description:**
When running checkout_externals on C6, ufs-weather-model could not be cloned without manually using git clone in the command line. 

**Solution:**
Use .gitmodules to load externals. Using this means we can get rid of externals.cfg. We have confirmed that this is NCO compliant.

**Requirements:**

**Acceptance Criteria (Definition of Done):**
Running .gitmodules should clone ufs-weather-model.

**Dependencies (Optional):**

**Alternative Solutions (Optional):**

**Comment by bbakernoaa** [comment]
should we add it to simply already have the submodules in the repository like global workflow did? This would simplify a lot of things for this as we already know the repositories needed.

**Comment by BrianCurtis-NOAA** [comment]
> should we add it to simply already have the submodules in the repository like global workflow did? This would simplify a lot of things for this as we already know the repositories needed.

Instead of a checkout externals, go with the .gitmodules? I would prefer that method. I think the only thing we'd have to check is if it meets EE2 requirements to go that route.

**Comment by AnnaSmoot-NOAA** [comment]
@BrianCurtis-NOAA How can we check if .gitmodules meets EE2 requirements?

**Comment by AnnaSmoot-NOAA** [comment]
Based on the emails from Jianping and Lin that .gitmodules meets NCO standards, I've updated this issue to reflect that.
